version: '3.9'

services:
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      METRICS_PORT: 8888
      NUMBER_OF_WORKERS: 2
      LARGE_TASK_PERCENTAGE: 1
      SMALL_TASK_MIN_SIZE: 0kb
      SMALL_TASK_MAX_SIZE: 6kb
      LARGE_TASK_MIN_SIZE: 100kb
      LARGE_TASK_MAX_SIZE: 300kb
      REDIS_URL: redis://redis:6379
      PUBLISHED_TASKS_QUEUE_NAME: tasks
      PUBLISHED_TASKS_QUEUE_MAX_SIZE: 6500
    expose:
      - 8888
    scale: 4

  redis:
    image: redis:6.2.6-alpine3.15
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
