version: '3.9'

services:
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    environment:
      METRICS_PORT: 8888
      NUMBER_OF_WORKERS: 2
      LARGE_TASK_PERCENTAGE: 1
      SMALL_TASK_MIN_SIZE: 0kb
      SMALL_TASK_MAX_SIZE: 6kb
      LARGE_TASK_MIN_SIZE: 100kb
      LARGE_TASK_MAX_SIZE: 300kb
    expose:
      - 8888
    scale: 2

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
