version: '3.9'

services:
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      METRICS_PORT: 8888
      NUMBER_OF_WORKERS: 2
      LARGE_TASK_PERCENTAGE:
      SMALL_TASK_MIN_SIZE:
      SMALL_TASK_MAX_SIZE:
      LARGE_TASK_MIN_SIZE:
      LARGE_TASK_MAX_SIZE:
      REDIS_URL: redis://redis:6379
      PUBLISHED_TASKS_QUEUE_NAME: tasks
      PUBLISHED_TASKS_QUEUE_MAX_SIZE: 6500
    expose:
      - 8888
    scale: 2

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      processor:
        condition: service_healthy
    environment:
      METRICS_PORT: 8888
      SELECTOR_MIN_DURATION_MS:
      SELECTOR_MAX_DURATION_MS:
      NUMBER_OF_PROCESSORS: 6
      INTERNAL_PROCESSOR_MIN_DURATION_MS:
      INTERNAL_PROCESSOR_MAX_DURATION_MS:
      EXTERNAL_PROCESSOR_GRPC_URL: processor:7777
      REDIS_URL: redis://redis:6379
      PUBLISHED_TASKS_QUEUE_NAME: tasks
      PROCESSING_TASKS_QUEUE_NAME: processing
    expose:
      - 8888
    scale: 2

  processor:
    build:
      context: .
      dockerfile: processor/Dockerfile
    environment:
      METRICS_PORT: 8888
      EXTERNAL_PROCESSOR_MIN_DURATION:
      EXTERNAL_PROCESSOR_MAX_DURATION:
    expose:
      - 7777
      - 8888
    scale: 2

  redis:
    image: redis:6.2.6-alpine3.15
    command: '--save "" --appendonly no'
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
