version: '3.9'
x-monitored: &monitored-service
  environment: &monitored-env
    METRICS_PORT: 8888
  expose:
    - 8888
x-messaging: &messaging-service
  depends_on: &messaging-depends
    redis:
      condition: service_healthy
    rabbitmq:
      condition: service_healthy
  environment: &messaging-env
    PUBLISHED_TASKS_QUEUE_NAME: tasks
    REDIS_URL: redis://redis:6379
    RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

services:
  producer:
    <<: *monitored-service
    <<: *messaging-service
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      <<: *monitored-env
      <<: *messaging-env
      STRATEGY:
      LARGE_TASK_PERCENTAGE:
      SMALL_TASK_MIN_SIZE:
      SMALL_TASK_MAX_SIZE:
      LARGE_TASK_MIN_SIZE:
      LARGE_TASK_MAX_SIZE:
      PUBLISHED_TASKS_QUEUE_MAX_SIZE: 2000
    scale: 2

  consumer:
    <<: *monitored-service
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      <<: *messaging-depends
      redis:
        condition: service_healthy
      processor:
        condition: service_healthy
    environment:
      <<: *monitored-env
      <<: *messaging-env
      SELECTOR_MIN_DURATION_MS:
      SELECTOR_MAX_DURATION_MS:
      NUMBER_OF_PROCESSORS: 6
      INTERNAL_PROCESSOR_MIN_DURATION_MS:
      INTERNAL_PROCESSOR_MAX_DURATION_MS:
      EXTERNAL_PROCESSOR_GRPC_URL: processor:7777
      PROCESSING_TASKS_QUEUE_NAME: processing
    scale: 2

  processor:
    <<: *monitored-service
    build:
      context: .
      dockerfile: processor/Dockerfile
    environment:
      <<: *monitored-env
      EXTERNAL_PROCESSOR_MIN_DURATION:
      EXTERNAL_PROCESSOR_MAX_DURATION:
    scale: 2

  redis:
    image: redis:6.2.6-alpine3.15
    command: '--save "" --appendonly no'
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    expose:
      - 5672
    ports:
      - "127.0.0.1:15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics --quiet ping

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
