global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'producer'
    dns_sd_configs:
      - names:
          - producer
        type: A
        port: 8888
  - job_name: 'consumer'
    dns_sd_configs:
      - names:
          - consumer
        type: A
        port: 8888
  - job_name: 'processor'
    dns_sd_configs:
      - names:
          - processor
        type: A
        port: 8888
